services:
  postgres:
    image: postgres:16
    container_name: code-arena
    environment:
      POSTGRES_DB: code-arena
      POSTGRES_USER: santiago
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: